import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { uniquePapers, sourceInput } from '../src/identity.ts';
import { enrichItem, createBibliographyIndex } from '../src/enrich.ts';
import type { ReviewsData, BibliographyData } from '../src/types.ts';
const data: ReviewsData = JSON.parse(await readFile('public/data/reviews-index.json', 'utf8'));
const bibliography: BibliographyData = JSON.parse(await readFile('public/data/bibliography.json', 'utf8'));
const now = new Date(), month = now.toISOString().slice(0, 7);
const lookup = createBibliographyIndex(bibliography.records);
const items = uniquePapers(data.items).map(item => enrichItem(item, {}, {}, lookup));
const missingAuthors = items.filter(item => !item.authors?.length).length;
const missingIds = items.filter(item => !sourceInput(item)).length;
const report = `# Review monthly maintenance — ${month}\n\nChecked at: ${now.toISOString()}\n\n- Upstream literature date: ${data.meta.updated}\n- Unique papers: ${items.length}\n- Papers with authors: ${items.length - missingAuthors}\n- Papers missing usable identifiers: ${missingIds}\n- Papers missing authors: ${missingAuthors}\n\n## Recurring work\n\n- Day 1: validate upstream literature, preserve bibliography overlay, refresh newly available citations, test and publish.\n- Day 3: update dependencies within declared compatible ranges, test and build, audit all dependencies including build tools, then publish allowlisted passing updates in a separate minimal job.\n- Every run retains logs and artifacts in GitHub Actions, including failures.\n\n## Follow-up priorities\n\n${missingIds ? `- Manually resolve ${missingIds} papers without safe identifiers; title-only guesses must not be published.\n` : ''}${missingAuthors ? `- Verify missing author metadata for ${missingAuthors} papers from primary records.\n` : ''}- Review browser regression failures and dependency advisories in this run before any manual retry.\n- Layout redesigns and medical conclusions require a separate scoped implementation; this schedule performs measurable maintenance.\n\nThis report contains public index statistics only. It does not access private workbench jobs, drafts, files, model credentials or analytics.\n`;
await mkdir('docs/maintenance', { recursive: true });
await writeFile(`docs/maintenance/${month}.md`, report);
console.log(report);
